@@include('files/vendors/vendors.js', {})
@@include('files/sliders.js', {})
@@include('files/functions.js', {})
@@include('files/dynamic-adapt.js', {})
@@include('files/forms.js', {})
@@include('files/script.js', {})
